import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen `}
      >
        <header>

          <div className=" p-[1em] fixed bg-white w-full z-100">
            <h1 className="text-2xl ">Elodie Rougeaux-Léaux</h1>
          </div>
        </header>
        <div className="pt-[2.8em] h-full">
          {children}
        </div>
        <footer>
          <div className=" mt-[10em] w-full text-end">
            <p className="text-sm ">© 2024 Elodie Rougeaux-Léaud</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
